name: Build and deploy app

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update version
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: |
          $Version = $github.ref;
          if ($Version.StartsWith("refs/tags/")) {
            $Version = $Version.SubString(10)
          }

          if (!$Version) {
            exit
          }
          
          function UpdateVersion {
            param($path)

            $content = Get-Content -Path $path -Raw
            $content = $content.Replace("#APP_VERSION#", $Version)

            Set-Content -Path $path -Value $content
          }

          UpdateVersion -path ./.env
          UpdateVersion -path ./public/serviceworker.js
          
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
